name-template: "v$NEXT_MAJOR_VERSION.$NEXT_MINOR_VERSION.$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_MAJOR_VERSION.$NEXT_MINOR_VERSION.$NEXT_PATCH_VERSION"

categories:
  - title: "### Added"
    labels: 
      - "feat"
      - "feature"
  - title: "### Fixed"
    labels:
      - "fix"
      - "bug"
  - title: "### Changed"
    labels: 
      - "chore"
      - "refactor"
  - title: "### Documentation"
    labels: 
      - "docs"
  - title: "### Tests"
    labels: 
      - "test"
  - title: "### CI/CD"
    labels: 
      - "ci"
      - "build"
  - title: "### Removed"
    labels: 
      - "remove"
      - "delete"

change-template: "- $TITLE by @$AUTHOR (#$NUMBER)"

template: |
  ## [$NEXT_VERSION]
  $CHANGES

  [$NEXT_VERSION]: https://github.com/vysf/geolistrik-cli/releases/tag/v$NEXT_VERSION
