name-template: "{$GITHUB_REF_NAME}"
tag-template: "{$GITHUB_REF_NAME}"
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
categories:
  - title: "### Added"
    labels: 
      - "feat"
      - "feature"
  - title: "### Fixed"
    labels:
      - "fix"
      - "bug"
  - title: "### Changed"
    labels: 
      - "chore"
      - "refactor"
  - title: "### Documentation"
    labels: 
      - "docs"
  - title: "### Tests"
    labels: 
      - "test"
  - title: "### CI/CD"
    labels: 
      - "ci"
      - "build"
  - title: "### Removed"
    labels: 
      - "remove"
      - "delete"

change-template: "- $TITLE by @$AUTHOR (#$NUMBER)"

template: |
  ## $NAME [$NAME]: https://github.com/$OWNER/$REPOSITORY/releases/tag/GITHUB_REF_NAME
  $CHANGES

  [$NAME]: https://github.com/$OWNER/$REPOSITORY/releases/tag/GITHUB_REF_NAME
