name: Generate Changelog

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.0.1
        with:
          mytoken: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{ github.ref_name }}
          reverse: false

      - name: Save changelog to file
        run: echo "${{ steps.changelog.outputs.changelog }}" > CHANGELOG.md

      - name: Commit and push changelog
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "docs: update changelog for ${{ github.ref_name }}"
          git push
