name: Release Geolistrik CLI

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka python-dotenv rich requests openpyxl
          pip install --only-binary=:all: pandas numpy matplotlib

      # Windows build dengan Nuitka + Inno Setup
      # default shell is PowerShell, see both VERSION and $VERSION get handled
      - name: Build Windows executable
        if: matrix.os == 'windows-latest'
        run: |
          $VERSION = "${{ github.ref_name }}".TrimStart("v") # "v1.0.0" -> "1.0.0"
          $versionInfo = "$VERSION.0"                        # jadi "1.0.0.0"
          echo "Replacing version in ISS..."
          (Get-Content geolistrik_setup.iss) -replace "{{VERSION}}", $VERSION | Set-Content geolistrik_setup.iss
          (Get-Content geolistrik_setup.iss) -replace "{{VERSION_INFO}}", $versionInfo | Set-Content geolistrik_setup.iss
          echo "Building with Nuitka..."
          nuitka --standalone --onefile --assume-yes-for-downloads --enable-plugin=pylint-warnings --enable-plugin=no-qt --include-package=geolistrik --windows-icon-from-ico=assets/icon.ico --output-dir=build geolistrik/__main__.py
          echo "Building installer with Inno Setup..."
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" geolistrik_setup.iss
          mkdir release-files
          mv output/geolistriksetup-$VERSION.exe release-files/

      # Linux build dengan Nuitka
      - name: Build Linux executable
        if: matrix.os == 'ubuntu-latest'
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          echo "Building with Nuitka..."
          nuitka --standalone --onefile --enable-plugin=pylint-warnings --enable-plugin=no-qt --include-package=geolistrik --output-dir=build geolistrik/__main__.py
          mkdir release-files
          mv build/__main__.bin release-files/geolistrik-linux-$VERSION.bin

      # Upload artifacts dari masing-masing OS
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-files-${{ matrix.os }}
          path: release-files/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-files
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-files/geolistriksetup-*.exe
            release-files/geolistrik-linux-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
